version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-warlocks
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: mongodb-warlocks
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user_db
      - MONGO_INITDB_ROOT_PASSWORD=warlocks
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo:/data/db

  redis:
    image: redis:latest
    container_name: redis-warlocks
    ports:
      - "6379:6379"


  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq-warlocks
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=user_rmq
  #     - RABBITMQ_DEFAULT_PASS=warlocks
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   volumes:
  #     - ./docker/rabbitmq:/var/lib/rabbitmq
