@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2JkYzBlNzgzZWVkM2MzM2JkNWM5YTEiLCJlbWFpbCI6ImphbmUuZG9lQGV4YW1wbGUuY29tIiwicm9sZXMiOlsiYWRtaW4iXSwiaWF0IjoxNzQwNjA5NjAwLCJleHAiOjE3NDA2MTMyMDB9.PUasDqYrPfWaZ9gYysnh_xukoiVSS82cLSuMwQK5lZU

### Login
POST http://localhost:5001/account/login
Content-Type: application/json

{
  "email": "jane.doe@example.com",
  "password": "password123"
}

### Create Admin Account (requires admin role)
POST http://localhost:5001/account/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Mary Hane Doe",
  "email": "mhane.doe@example.com",
  "bio": "This is a bio",
  "password": "password123",
  "status": 1,
  "avatar": "https://fakeimg.pl/600x400?text=avatar",
  "roles": ["author"]
}

### Update Admin Account (requires admin role)
PUT http://localhost:5001/account/update
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "accountId": "67baa6595bf32d6cab827acc",
  "name": "Luna Jane Doe"
}

### Get All Accounts (requires admin role)
GET http://localhost:5001/account/all
Authorization: Bearer {{token}}

### Create Author Profile (Public endpoint)
POST http://localhost:5001/account/signup
Content-Type: application/json

{
  "name": "2Jane Doe",
  "email": "2jane.doe@example.com",
  "bio": "This is a bio",
  "password": "password123",
  "avatar": "https://fakeimg.pl/600x400?text=WAR"
}

### Update Author Profile (requires auth token)
PUT http://localhost:5001/account/updateprofile
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "accountId": "67bb2063af40f6ff71930d50",
  "bio": "My name is optumus prime"
}

### Get One Profile by Id (requires auth token)
GET http://localhost:5001/account/profile/67bdc0e783eed3c33bd5c9a1
Authorization: Bearer {{token}}



### Check token health by Id
POST http://localhost:5001/account/checktoken
Authorization: Bearer {{token}}

{
  "accountId": "67bdc0e783eed3c33bd5c9a1",
}

### Health Check
GET http://localhost:5001/account/health