@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2JkMWU1MjE4NWUyNTQ5NDI3NzM3NDgiLCJlbWFpbCI6Im1qYW5lLmRvZUBleGFtcGxlLmNvbSIsInJvbGVzIjpbImF1dGhvciJdLCJpYXQiOjE3NDA0ODM1OTIsImV4cCI6MTc0MDQ4NzE5Mn0.l6wcEYR6nOWgSnZqWM8XsfKLlVVtj-MqW_48GiR8cHE

### Login public endpoint
POST http://localhost:5001/account/login
Content-Type: application/json

{
  "email": "mjane.doe@example.com",
  "password": "password123"
}

### Create Article (requires athenticated user)
POST http://localhost:5001/articles/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Oh my God, this is a new article",
  "content": "Lorem ipsum",
  "cover": "https://fakeimg.pl/600x400?text=cover",
  "tags": ["dev", "node", "react"]
}

### Update Article (requires athenticated user)
PUT http://localhost:5001/articles/update/67bd3c32b466408285313a8f
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "How to create an Awesome App with React and Node.js",
  "content": "Lorem ipsum, dollor sit amet",
  "cover": "https://fakeimg.pl/600x400?text=cover",
  "tags": ["node", "react"]
}

### Update Likes (requires athenticated user)
GET http://localhost:5001/articles/updatelike/67bd3c32b466408285313a8f HTTP/1.1
Authorization: Bearer {{token}}

### Delete Article (requires athenticated user)
DELETE http://localhost:5001/articles/delete/dsfasdfa HTTP/1.1
Authorization: Bearer {{token}}

### Get all articles with pagination
GET http://localhost:5001/articles/all?page=1&limit=10 HTTP/1.1

### Show Article by Slug
GET http://localhost:5001/articles/article-title-f0f8913e-a206-43c7-9c27-f1c2d9c7c587 HTTP/1.1

### Search Articles
POST http://localhost:5001/articles/search
Content-Type: application/json

{
  "title": "how"
}

